<?php

return [
    'slug' => 'chatbot',
    'version' => '1.0.0',

    'messages' => [
        'page_size' => (int) env('CHATBOT_PAGE_SIZE', 40),
        'max_fetch' => (int) env('CHATBOT_MESSAGES_MAX_FETCH', 300),
        'max_text_length' => (int) env('CHATBOT_MAX_TEXT_LENGTH', 10000),
        'max_file_size_kb' => (int) env('CHATBOT_MAX_FILE_SIZE_KB', 10240),
        'allowed_extensions' => [
            'jpg',
            'jpeg',
            'png',
            'webp',
            'gif',
            'pdf',
            'txt',
            'zip',
            'docx',
            'xlsx',
        ],
        'allowed_mimes' => [
            'image/jpeg',
            'image/png',
            'image/webp',
            'image/gif',
            'application/pdf',
            'text/plain',
            'application/zip',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        ],
        'storage_disk' => env('CHATBOT_STORAGE_DISK', 'public'),
        'storage_path' => env('CHATBOT_STORAGE_PATH', 'chatbot/messages'),
    ],

    'ui' => [
        'icon_choices' => [
            'fa-comments',
            'fa-hashtag',
            'fa-bullhorn',
            'fa-briefcase',
            'fa-chart-line',
            'fa-users',
            'fa-rocket',
            'fa-lightbulb',
            'fa-headset',
            'fa-gear',
            'fa-code',
            'fa-handshake',
        ],
        'color_palette' => [
            '#0ea5e9',
            '#2563eb',
            '#7c3aed',
            '#9333ea',
            '#ec4899',
            '#ef4444',
            '#f97316',
            '#eab308',
            '#22c55e',
            '#14b8a6',
            '#0f172a',
            '#64748b',
        ],
    ],

    'socket' => [
        'enabled' => filter_var(env('CHATBOT_SOCKET_IO_ENABLED', true), FILTER_VALIDATE_BOOL),
        'client_url' => env('CHATBOT_SOCKET_IO_URL', 'http://127.0.0.1:6003'),
        'path' => env('CHATBOT_SOCKET_IO_PATH', '/socket.io'),
        'namespace' => env('CHATBOT_SOCKET_IO_NAMESPACE', '/'),
        'emit_url' => env('CHATBOT_SOCKET_IO_EMIT_URL', 'http://127.0.0.1:6003/emit'),
        'server_token' => env('CHATBOT_SOCKET_IO_SERVER_TOKEN'),
        'transports' => ['websocket', 'polling'],
    ],
];
